AllCops:
  Exclude:
    - app/**/*.haml
    - db/schema.rb

#https://github.com/bbatsov/rubocop/blob/master/config/default.yml

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/MethodLength:
  CountComments: false
  Max: 30

Style/SymbolArray:
  Enabled: false

Metrics/ParameterLists:
  Enabled: true
  CountKeywordArgs: false

Style/DoubleNegation:
  Enabled: false

Style/PredicateName:
  NamePrefix:
    - is_
    - has_

  NamePrefixBlacklist:
    - is_
    - has_

Metrics/AbcSize:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 10

Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - tmp/**/*
    - vendor/**/*
    - spec/teaspoon_env.rb

Style/AsciiComments:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/ExtraSpacing:
  AllowForAlignment: true

Style/NegatedIf:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Delegate:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/IndentArray:
  Enabled: true
  EnforcedStyle: consistent

Style/IndentHash:
  Enabled: true
  EnforcedStyle: consistent

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/EmpthyMethod:
  Enabled: false
